gravitacia-dev
jbeder/yaml-cpp pull request #1168
Opened 2023-01-29 22:38 UTC by gravitacia

2023-01-29 23:09 UTC, jbeder commented
You have a lot of random files in this commit. Could you please only include the relevant changes?

2023-01-30 09:00 UTC, gravitacia commented
> You have a lot of random files in this commit. Could you please only include the relevant changes?

fixed

2023-03-21 18:16 UTC, Osteri commented
aa

2023-08-10 19:42 UTC, jbeder requested changes
Please update the PR description to describe this change.

2023-08-10 19:42 UTC, jbeder commented on .gitignore
> +cmake-build-debug/
Please drop this file's changes.

2023-08-10 19:42 UTC, jbeder commented on include/yaml-cpp/emitter.h
> +    stream << std::fixed << std::setprecision(1) << value;
I *think* I see what you're trying to do, but could you please add a test that demonstrates this change?

2023-08-10 19:42 UTC, jbeder commented on include/yaml-cpp/emitter.h
> +  }else if (!special) {
Missing space between `}` and `else`.

2024-12-02 13:55 UTC, closed without merging