fix(src): avoid possible infinite loop in LoadAll().
jbeder/yaml-cpp pull request #1319
Opened 2024-09-12 12:32 UTC by FedeDP

Leave at first empty root.

This avoids an infinite loop in case of `HandleNextDocument` returning true even if the document has errors, basically because no `token.type` gets matched in `SingleDocParser::HandleNode`, leading to [`eventHandler.OnNull(mark, anchor);`](https://github.com/jbeder/yaml-cpp/blob/master/src/singledocparser.cpp#L145) being called indefinitely at each iteration, pushing a null node to documents vector.
Another solution would be to had a `m_scanner.pop();` in the `default` switch case in `SingleDocParser::HandleNode` so that we make sure to always consume the current token.

The behavior causes this issue: https://github.com/falcosecurity/falco/issues/3281

Easily reproducible with a simple c++ example:
```C++
#include <yaml-cpp/yaml.h>
#include <iostream>

int main() {
    static const std::string yml = R"(
,
    )";
    try {
	auto config = YAML::LoadAll(yml);
    } catch(const YAML::BadFile& e) {
        std::cerr << e.msg << std::endl;
        return 1;
    } catch(const YAML::ParserException& e) {
        std::cerr << e.msg << std::endl;
        return 1;
    }
    return 0;
}
```

2024-09-12 17:33 UTC, jbeder requested changes
Can you add a test (e.g., the code in the PR description)? Something that infinite-loops before this PR but doesn't after.

2024-09-13 07:00 UTC, FedeDP commented
Added the test; please note that if #1318 is merged first, i'll need to rebase this PR on master and fix up the test (that will then throw a `ParserException` obviously).

2024-09-13 08:19 UTC, jbeder commented
Merged the other one. Go ahead and rebase this and then ping me.

2024-09-13 08:24 UTC, FedeDP commented
@jbeder done! 
Thanks for the quick response!

2024-10-10 13:07 UTC, FedeDP commented
Sorry for the ping @jbeder , any news on this one? :) 
Thanks!

2024-10-10 15:06 UTC, jbeder requested changes
Sorry for the delay. It looks like I forgot to hit "send" on the review itself - github's UI is terrible :(

2024-10-14 07:20 UTC, FedeDP commented on test/integration/node_spec_test.cpp
> +TEST(NodeSpecTest, Ex7_25_InfiniteLoopNodes) {
Done :) 
Thanks for the feedback! (and agree about github's UI :/ )

2024-10-14 07:30 UTC, FedeDP commented on test/integration/node_spec_test.cpp
> +TEST(NodeSpecTest, Ex7_25_InfiniteLoopNodes) {
I see 2 CI failures that don't seem to be caused by my commits:
> /usr/include/gtest/internal/gtest-port.h:279:2: error: #error C++ versions less than C++14 are not supported.
  279 | #error C++ versions less than C++14 are not supported.

2024-10-29 13:09 UTC, leogr commented
Hey @jbeder 

Any update on this?

2024-10-30 03:20 UTC, jbeder approved these changes

2024-10-30 03:21 UTC, merged